#!/bin/bash
set -e
dotnet restore ./Il2CppInspector.CLI/Il2CppInspector.CLI.csproj -r osx-arm64
dotnet publish -c Release --no-self-contained --no-restore -o ./osx-arm64 -r osx-arm64 ./Il2CppInspector.CLI/Il2CppInspector.CLI.csproj
cp il2cpp pogo ./osx-arm64/
chmod +x ./osx-arm64/il2cpp ./osx-arm64/pogo
echo "add to path: $PWD/osx-arm64"
# cd ~/Desktop/projects/pgtools/apks/0.367.2
# rm -rf output
# il2cpp
# ls output/Code/holo-game/Niantic/Platform/NianticInventoryCache*